select * from customer limit 20

--Q1. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating:: numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average purchase amounts between standard and express shipping.
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('St')